### ISSUE TITLE
Hot Reloading With Single-Spa

### ISSUE THREAD

**Issue by chrisbrooks** [CanopyTax/single-spa-canopy#27]
Hi, 

I have been using single-spa-react but I can't work out how to get hot reloading working for my micro app when it's being used in the main application. I came across this repo/package and was wondering how it actually works and if you guys are using it in practice?

Thanks

**Comment by joeldenning** [comment]
Hi Chris,

This package is specific to Canopy in ways that make it not reusable for other organizations. You could look at the code for an example of hot reloading can work, but I wouldn't recommend actually using it.

For some recent discussion about hot reloading with a code example, see https://github.com/CanopyTax/single-spa/issues/337
